<div class="nav_local">
<a class="nav_local_list" href="<?php echo home_url('aboutmike'); ?>"><span class="nav_local_list_ja">マイク先生のこと</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="英語、英会話教師のマイク・ニマ先生についてとご挨拶はこちら。" width="15" height="15" loading="lazy" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_about_mike.svg"><em class="middle_About_Mike first_letter">A</em>bout Mike</span></a>
<a class="nav_local_list" href="<?php echo home_url('one-to-one'); ?>"><span class="nav_local_list_ja">個人レッスン</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="マンツーマンで英会話・英語レッスンを受けられます。" width="15" height="15" loading="lazy" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_one_to_one.svg"><em class="middle_One_to_One first_letter">O</em>ne to One</span></a>
<a class="nav_local_list" href="<?php echo home_url('online'); ?>"><span class="nav_local_list_ja">オンラインレッスン</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="オンラインで英会話・英語レッスンを受けられます。" width="15" height="15" loading="lazy" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_online.svg"><em class="middle_Online_Lessons first_letter">O</em>nline Lessons</span></a>
<a class="nav_local_list" href="<?php echo home_url('gallery'); ?>"><span class="nav_local_list_ja">ギャラリー</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="英会話教室の生徒さんやマイク先生による写真ギャラリーです。" loading="lazy" width="15" height="15" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_gallery.svg"><em class="middle_Gallery first_letter">G</em>allery</span></a>
<a class="nav_local_list" href="<?php echo home_url('gallery/lessonpix'); ?>"><span class="nav_local_list_ja">教室の様子</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="英会話教室札幌の様子。英語、英会話のレッスン風景などです。" loading="lazy" width="15" height="15" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_gallery.svg"><em class="middle_Gallery_Lessonpix first_letter">G</em>allery<span class="vertical_bar"> | </span>Lessonpix</span></a>
<a class="nav_local_list" href="<?php echo home_url('gallery/scrapbook'); ?>"><span class="nav_local_list_ja">マイク先生のスクラップブック</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="英語・英会話教師マイク先生が撮った写真のスクラップブックです。" width="15" height="15" loading="lazy" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_gallery.svg"><em class="middle_Gallery_Scrapbook first_letter">G</em>allery<span class="vertical_bar"> | </span>Scrapbook</span></a>
<a class="nav_local_list" href="<?php echo home_url('translations'); ?>"><span class="nav_local_list_ja">ネイティブ英訳</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="ネイティブスピーカー、英語・英文学教師による英語翻訳です。" loading="lazy" width="15" height="15" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_translations.svg"><em class="middle_Translations first_letter">T</em>ranslations</span></a>
<a class="nav_local_list" href="<?php echo home_url('location'); ?>"><span class="nav_local_list_ja">所在地</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="マイク英会話教室札幌は札幌市中央区中島公園の近くにあります。詳しくはこちらをご覧ください。" loading="lazy" width="15" height="15" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_location.svg"><em class="middle_Location first_letter">L</em>ocation</span></a>
<a class="nav_local_list" href="<?php echo home_url('reviews'); ?>"><span class="nav_local_list_ja">生徒さんの声</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="マイク英会話教室札幌の生徒さんたちの声です。" loading="lazy" width="15" height="15" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_reviews.svg"><em class="middle_Reviews first_letter">R</em>eviews</span></a>
<a class="nav_local_list" href="<?php echo home_url('reviews/one-to-one'); ?>"><span class="nav_local_list_ja">個人レッスンレビュー</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="マイク英会話教室札幌の個人レッスンレビューです。" width="15" height="15" loading="lazy" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_reviews.svg"><em class="middle_Reviews_One_to_One first_letter">R</em>eviews<span class="vertical_bar"> | </span>One to One</span></a>
<a class="nav_local_list" href="<?php echo home_url('reviews/translations'); ?>"><span class="nav_local_list_ja">ネイティブ英訳レビュー</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="マイク英会話教室札幌のネイティブ英訳レビューです。" width="15" height="15" loading="lazy" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_reviews.svg"><em class="middle_Reviews_Translations first_letter">R</em>eviews<span class="vertical_bar"> | </span>Translations</span></a>
<a class="nav_local_list" href="<?php echo home_url('mikes-posts'); ?>"><span class="nav_local_list_ja">ブログ</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="英語・英会話教師マイク先生のブログです。" width="15" height="15" loading="lazy" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_mikes_posts.svg"><em class="middle_Mikes_Posts first_letter">M</em>ike's Posts</span></a>
<a class="nav_local_list" href="<?php echo home_url('contact'); ?>"><span class="nav_local_list_ja">お問い合わせ</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="マイク英会話教室札幌へのお問い合わせはこちらからお願いいたします。英語でも日本語でも大丈夫です。" width="15" height="15" loading="lazy" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_contact.svg"><em class="middle_Contact first_letter">C</em>ontact</span></a>
<a class="nav_local_list" href="<?php echo home_url('english'); ?>"><span class="nav_local_list_ja">英語 中国語 韓国語</span><span class="nav_local_list_en"><img class="nav_local_icon" alt="英語 中国語 韓国語はこちらから。" width="15" height="15" loading="lazy" src="<?php echo get_template_directory_uri(); ?>/common/img/icon_sec_english.svg"><em class="middle_English first_letter">E</em>nglish 中文 한국어</span></a>
</div><!-- nav_local -->
